version: "3"

services:
  nginx:
    build: nginx
    container_name: "nginx"
    ports:
      - "8080:80"
    restart: always
    volumes:
      - ../src:/var/www
    depends_on:
      - php-fpm

  php-fpm:
    build: php-fpm
    environment:
      PHP_IDE_CONFIG: "serverName=docker-debug"
    container_name: "php-fpm"
    restart: always
    volumes:
      - ../src:/var/www
    working_dir: /var/www
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.25
    container_name: "mysql"
    ports:
      - 33306:3306
    restart: always
    volumes:
      - ../mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: template
      MYSQL_USER: template-user
      MYSQL_PASSWORD: template-password
      MYSQL_ROOT_PASSWORD: root
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci